server:
  port: 5000

spring:
  application:
    name: sweet-home
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ######
    password: ######
    url: ######
  redis:
    host: ######
    port: ######
    password: ######
    timeout: ######
# MyBaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_UUID
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

dingding:
  webhook: ######
log-reader:
  path: ./gitdatsanvich.log
chat-gpt:
  key: ######
  url:
    models: https://api.openai.com/v1/models
    talk: https://api.openai.com/v1/chat/completions
