server:
  port: 5000

spring:
  application:
    name: sweet-home
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: 老子数据库能让你瞅着？
#    password: 老子数据库能让你瞅着？
#    url: 老子数据库能让你瞅着？
# MyBaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_UUID
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

dingding:
  webhook: ######
log-reader:
  path: ./gitdatsanvich.log
